package infs7205.gu.practice_2.mapper;

import infs7205.gu.practice_2.model.Chipotle;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ChipotleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    int insert(Chipotle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    int insertSelective(Chipotle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    Chipotle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chipotle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chipotle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chipotle row);

    List<Chipotle> selectChipotle(@Param("latitude")double latitude, @Param("longitude")double longitude, @Param("num")Integer num);

    List<Chipotle> selectChipotleByRectangle(@Param("minLat")double minLat,@Param("minLng")double minLng, @Param("maxLat")double maxLat, @Param("maxLng")double maxLng);

    List<Chipotle> selectChipotleByCorridor(double Lat1, double Lng1, double Lat2, double Lng2, double radius);


    String selectCorridorGeo(double Lng1, double Lat1, double Lng2, double Lat2, double radius);
}