package infs7205.gu.practice_2.model;

public class Chipotle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chipotle.geom
     *
     * @mbg.generated
     */
    private Object geom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.id
     *
     * @return the value of chipotle.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.id
     *
     * @param id the value for chipotle.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.state
     *
     * @return the value of chipotle.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.state
     *
     * @param state the value for chipotle.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.location
     *
     * @return the value of chipotle.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.location
     *
     * @param location the value for chipotle.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.address
     *
     * @return the value of chipotle.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.address
     *
     * @param address the value for chipotle.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.latitude
     *
     * @return the value of chipotle.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.latitude
     *
     * @param latitude the value for chipotle.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.longitude
     *
     * @return the value of chipotle.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.longitude
     *
     * @param longitude the value for chipotle.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chipotle.geom
     *
     * @return the value of chipotle.geom
     *
     * @mbg.generated
     */
    public Object getGeom() {
        return geom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chipotle.geom
     *
     * @param geom the value for chipotle.geom
     *
     * @mbg.generated
     */
    public void setGeom(Object geom) {
        this.geom = geom;
    }
}